spring.application.name=Banking
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/banking_db 
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

 JWT_SECRET=my-super-secret-key-for-banking-system-123456789
 logging.level.org.springframework.security=DEBUG